Controllers/SachOnlineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SachOnline.Models;

namespace SachOnline.Controllers
{
    public class SachOnlineController : Controller
    {
        dbSachOnlineDataContext data = new dbSachOnlineDataContext();
        private List<Book> LaySachMoi(int count)
        {
            return data.Books.OrderByDescending(a =>
            a.Publication_date).Take(count).ToList();
        }
        // GET: SachOnline
        public ActionResult Index()
        {
            var listSachMoi = LaySachMoi(6);
            return View(listSachMoi);
        }
        // GET: SachOnline
        public ActionResult SachBanNhieuPartial()
        {
            var listSachBanNhieu = from cd in data.SachBanNhieus select cd;
            return PartialView(listSachBanNhieu);
        }
        public ActionResult ChuDePartial() {
            var listChuDe = from cd in data.ChuDes select cd;
            return PartialView(listChuDe);
        }
        public ActionResult NhaXuatBanPartial()
        {
            var listNhaXuatBan = from cd in data.Publishers select cd;
            return PartialView(listNhaXuatBan);
        }
    }
}

Views/Shared/ChuDePartial.cshtml
@model IEnumerable<SachOnline.Models.ChuDe>
<ul class="list-group">
    <li class="list-group-item active" style="font-weight:bold; text-align:center">SÁCH THEO CHỦ ĐỀ</li>
    @foreach(var item in Model){
        <a href="@Url.Action("SachTheoChuDe","SachOnline",new {id = item.MaChuDe})" class="list-group-item">
            @item.TenChuDe
        </a> 
    }
</ul>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style type="text/css">
        .imgbook {
            transition: all 1s ease-in;
            width: 350px;
        }

            .imgbook:hover {
                transform: scale(O.9);
                cursor: pointer;
            }

        .imgsachbannhieu {
            width: 100px;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>

    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
        @Html.Action("NhaXuatBanPartial", "SachOnline")
        @Html.Action("ChuDePartial", "SachOnline")
    </div>

    <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
        @RenderBody();
    </div>
</body>
</html>